// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pdp.ControlPlane.Ipam;

#nullable disable

namespace Pdp.ControlPlane.Ipam.Migrations
{
    [DbContext(typeof(IpamDbContext))]
    partial class IpamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ipam")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pdp.ControlPlane.Ipam.Entities.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<IPNetwork>("Network")
                        .HasColumnType("cidr")
                        .HasColumnName("network");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<short>("PrefixLength")
                        .HasColumnType("smallint")
                        .HasColumnName("prefix_length");

                    b.HasKey("Id")
                        .HasName("pk_allocation");

                    b.HasIndex("PoolId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_allocation_pool_name");

                    b.ToTable("allocation", "ipam");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Ipam.Entities.RegionPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<IPNetwork?>("HubCarveout")
                        .HasColumnType("cidr")
                        .HasColumnName("hub_carveout");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<short>("RegionIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("region_index");

                    b.Property<IPNetwork>("Supernet")
                        .HasColumnType("cidr")
                        .HasColumnName("supernet");

                    b.HasKey("Id")
                        .HasName("pk_region_pool");

                    b.HasIndex("Region")
                        .IsUnique()
                        .HasDatabaseName("ix_region_pool_region");

                    b.HasIndex("RegionIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_region_pool_region_index");

                    b.ToTable("region_pool", "ipam");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Ipam.Entities.Allocation", b =>
                {
                    b.HasOne("Pdp.ControlPlane.Ipam.Entities.RegionPool", "Pool")
                        .WithMany("Allocations")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_allocation_region_pool_pool_id");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Ipam.Entities.RegionPool", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
