#Requires -Version 5.1
<#
.SYNOPSIS
  Apply the ipam + registry EF Core schemas to the private control-plane ledger, in-VNet, as the Entra
  admin. The DB bring-up step that must run BEFORE bootstrap-postgres-principals.ps1 (the grants target
  these schemas/tables, so the schemas have to exist first). Spec: control-plane live data-layer bring-up.

.DESCRIPTION
  The ledger Postgres is private (VNet-injected) + Entra-only, so migrations cannot run from a laptop.
  This runs the production EF migrations as idempotent SQL (scripts/migrations/{ipam,registry}.sql,
  generated by `dotnet ef migrations script --idempotent`) inside a short-lived Manual ACA Job in the
  ledger's VNet, exactly like bootstrap-postgres-principals.ps1. YOU stay on your laptop; az is a
  control-plane call; the psql runs in the Job. Your oss-rdbms token (minted as the Entra ADMIN) rides
  in as a Job SECRET and is the psql "password". Tables are created OWNED BY THE ADMIN; the per-app UAMI
  grants (bootstrap step) then grant the apps DML on them. The Job self-deletes on success.

  Runs against the `pdp` database (created by the infra/control-plane Tofu `databases` block). Idempotent
  — the EF scripts guard every migration on __EFMigrationsHistory and the seed is ON CONFLICT DO NOTHING,
  so re-running is a no-op.

  ASCII-only on purpose so it parses identically under Windows PowerShell 5.1 and PowerShell 7.

.PARAMETER PgBootImage
  psql image. Public Docker Hub by default; override if Docker Hub pulls are blocked (e.g. an ACR mirror).

.EXAMPLE
  az login                 # as the Postgres Entra ADMIN
  cd infra/control-plane-host
  ./scripts/run-migrations.ps1
  ./scripts/bootstrap-postgres-principals.ps1   # then the principals + grants
#>
[CmdletBinding()]
param(
  [string] $PgBootImage = 'postgres:16-alpine'
)

$ErrorActionPreference = 'Continue'   # az writes warnings to stderr; under 'Stop' those become terminating
# NativeCommandErrors before 2>$null can discard them. This script checks $LASTEXITCODE explicitly.

function Write-Step($m) { Write-Host ">> $m" -ForegroundColor Cyan }
function Write-Ok($m) { Write-Host "[OK] $m" -ForegroundColor Green }
function Die($m) { Write-Host "[X] $m" -ForegroundColor Red; exit 1 }
function Assert-LastExit($m) { if ($LASTEXITCODE -ne 0) { Die $m } }

foreach ($t in @('az', 'tofu')) {
  if (-not (Get-Command $t -ErrorAction SilentlyContinue)) { Die "$t not found on PATH" }
}

# Operate on THIS stack regardless of caller cwd; $PSScriptRoot is .../scripts, the stack is its parent.
Set-Location -Path (Join-Path $PSScriptRoot '..')

$MigrationsDir = Join-Path $PSScriptRoot 'migrations'
$IpamSql = Join-Path $MigrationsDir 'ipam.sql'
$RegistrySql = Join-Path $MigrationsDir 'registry.sql'
foreach ($f in @($IpamSql, $RegistrySql)) {
  if (-not (Test-Path -LiteralPath $f)) {
    Die "missing $f - regenerate with: dotnet ef migrations script --idempotent --context <Ctx> --output $f"
  }
}

Write-Step 'Reading stack coordinates from tofu output...'
$ctxJson = tofu output -json bootstrap_context 2>$null
if ($LASTEXITCODE -ne 0 -or -not $ctxJson) {
  Write-Step 'tofu backend not initialized here - running "tofu init -reconfigure" (read-only)...'
  tofu init -reconfigure -input=false | Out-Null
  Assert-LastExit 'tofu init failed - run from infra/control-plane-host, check az login + state storage access'
  $ctxJson = tofu output -json bootstrap_context 2>$null
}
if ($LASTEXITCODE -ne 0 -or -not $ctxJson) {
  Die 'no "bootstrap_context" output - the host stack is NOT applied. Deploy infra/control-plane-host first.'
}
$ctx = $ctxJson | ConvertFrom-Json
$RG = $ctx.resource_group
$EnvId = $ctx.aca_environment_id
$PgFqdn = $ctx.ledger_fqdn
$PgDb = $ctx.postgres_database
if (-not ($RG -and $EnvId -and $PgFqdn -and $PgDb)) {
  Die "incomplete bootstrap_context (rg=$RG env=$EnvId host=$PgFqdn db=$PgDb)"
}

$Location = az group show -n $RG --query location -o tsv
Assert-LastExit "could not resolve location for RG $RG"

Write-Step 'Confirming Azure sign-in (must be the Postgres Entra admin)...'
$Upn = az account show --query user.name -o tsv
Assert-LastExit 'not signed in - run: az login'
Write-Ok "Signed in as: $Upn  (this identity MUST be the ledger's Entra admin)"

Write-Step 'Minting oss-rdbms access token...'
$Token = az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv
Assert-LastExit 'could not get an oss-rdbms token'

# base64 each script (single line, no special chars) so it rides in a Job env var without YAML/CLI quoting.
$IpamB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($IpamSql))
$RegistryB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($RegistrySql))

$job = 'caj-pgmigrate'
Write-Step "Cleaning any leftover job '$job' (idempotent)..."
az containerapp job delete -n $job -g $RG --yes 2>$null | Out-Null

Write-Step "Creating transient in-VNet ACA Job '$job' (applies ipam then registry against '$PgDb')..."
# The backtick before $VARs keeps them LITERAL in YAML - expanded by the container's /bin/sh at runtime.
$yaml = @"
location: $Location
properties:
  environmentId: $EnvId
  configuration:
    triggerType: Manual
    replicaTimeout: 600
    replicaRetryLimit: 0
    manualTriggerConfig:
      parallelism: 1
      replicaCompletionCount: 1
    secrets:
      - name: pgtoken
        value: "$Token"
  template:
    containers:
      - name: pgmigrate
        image: $PgBootImage
        resources:
          cpu: 0.5
          memory: 1.0Gi
        command: ["/bin/sh", "-c"]
        args:
          - 'set -e; echo "Applying ipam..."; echo "`$IPAM_B64" | base64 -d | psql -v ON_ERROR_STOP=1 -f -; echo "Applying registry..."; echo "`$REGISTRY_B64" | base64 -d | psql -v ON_ERROR_STOP=1 -f -; echo "Migrations applied."'
        env:
          - name: PGHOST
            value: "$PgFqdn"
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: "$PgDb"
          - name: PGUSER
            value: "$Upn"
          - name: PGSSLMODE
            value: "require"
          - name: PGPASSWORD
            secretRef: pgtoken
          - name: IPAM_B64
            value: "$IpamB64"
          - name: REGISTRY_B64
            value: "$RegistryB64"
"@
$yamlPath = [IO.Path]::GetTempFileName()
# UTF-8 WITHOUT BOM on PS 5.1 and 7 (5.1's Set-Content -Encoding utf8 writes a BOM that az --yaml rejects).
[IO.File]::WriteAllText($yamlPath, $yaml, (New-Object Text.UTF8Encoding($false)))
try {
  az containerapp job create -n $job -g $RG --yaml $yamlPath | Out-Null
  Assert-LastExit 'job create failed'
}
finally {
  Remove-Item $yamlPath -ErrorAction SilentlyContinue
}

Write-Step 'Starting the Job...'
$exec = az containerapp job start -n $job -g $RG --query name -o tsv
Assert-LastExit 'job start failed'

Write-Step "Waiting for execution '$exec'..."
$status = ''
for ($i = 0; $i -lt 120; $i++) {
  $status = az containerapp job execution list -n $job -g $RG `
    --query "[?name=='$exec'].properties.status | [0]" -o tsv 2>$null
  if ($status -in @('Succeeded', 'Failed')) { break }
  Start-Sleep -Seconds 5
}

if ($status -eq 'Succeeded') {
  Write-Ok 'ipam + registry schemas applied (execution Succeeded).'
  az containerapp job delete -n $job -g $RG --yes 2>$null | Out-Null
  Write-Ok 'Next: ./scripts/bootstrap-postgres-principals.ps1 (registers the UAMI principals + grants).'
}
else {
  $shownStatus = if ($status) { $status } else { 'unknown' }
  Write-Host "[X] execution status: $shownStatus - fetching logs..." -ForegroundColor Red
  az containerapp job logs show -n $job -g $RG --container pgmigrate --execution $exec --tail 200 2>$null
  Write-Host "  Job '$job' left in place for inspection; delete with: az containerapp job delete -n $job -g $RG --yes"
  Die 'migration failed'
}
