// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pdp.ControlPlane.Registry;

#nullable disable

namespace Pdp.ControlPlane.Registry.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    [Migration("20260702185823_WorkloadCatalog")]
    partial class WorkloadCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registry")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Archetype", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_archetypes");

                    b.ToTable("archetypes", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ArchetypeVersion", b =>
                {
                    b.Property<string>("ArchetypeName")
                        .HasColumnType("text")
                        .HasColumnName("archetype_name");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ModulePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_path");

                    b.Property<string>("ParameterSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameter_schema");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("ArchetypeName", "Version")
                        .HasName("pk_archetype_versions");

                    b.ToTable("archetype_versions", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.CatalogSync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_catalog_syncs");

                    b.ToTable("catalog_syncs", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Environment", b =>
                {
                    b.Property<Guid>("EnvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("env_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<IPNetwork?>("SpokeCidr")
                        .HasColumnType("cidr")
                        .HasColumnName("spoke_cidr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EnvId")
                        .HasName("pk_environments");

                    b.HasIndex("Kind", "Subscription", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_environment_natural_key");

                    b.ToTable("environments", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ProvisioningRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DispatchInputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dispatch_inputs");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("EnvId")
                        .HasColumnType("uuid")
                        .HasColumnName("env_id");

                    b.Property<long?>("GitHubRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_run_id");

                    b.Property<string>("GitHubRunUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_run_url");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("PlanSummary")
                        .HasColumnType("text")
                        .HasColumnName("plan_summary");

                    b.Property<string>("TrackedBy")
                        .HasColumnType("text")
                        .HasColumnName("tracked_by");

                    b.Property<string>("WorkflowFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_file");

                    b.HasKey("RunId")
                        .HasName("pk_provisioning_runs");

                    b.HasIndex("EnvId")
                        .HasDatabaseName("ix_provisioning_runs_env_id");

                    b.HasIndex("EnvId", "GitHubRunId")
                        .IsUnique()
                        .HasDatabaseName("uq_provisioning_run_github_run")
                        .HasFilter("github_run_id IS NOT NULL");

                    b.ToTable("provisioning_runs", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.WorkloadDetails", b =>
                {
                    b.Property<Guid>("EnvId")
                        .HasColumnType("uuid")
                        .HasColumnName("env_id");

                    b.Property<string>("ArchetypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archetype_name");

                    b.Property<string>("ArchetypeVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archetype_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("PdpEnv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdp_env");

                    b.Property<string>("SpokeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spoke_name");

                    b.Property<string>("SpokeSubscription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spoke_subscription");

                    b.HasKey("EnvId")
                        .HasName("pk_workloads");

                    b.HasIndex("ArchetypeName", "ArchetypeVersion")
                        .HasDatabaseName("ix_workloads_archetype_name_archetype_version");

                    b.HasIndex("SpokeSubscription", "SpokeName")
                        .HasDatabaseName("ix_workloads_spoke");

                    b.ToTable("workloads", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.EnvironmentSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("text")
                        .HasColumnName("current_phase");

                    b.Property<Guid?>("CurrentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_run_id");

                    b.Property<bool>("PendingConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("pending_confirmation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_environment_saga");

                    b.ToTable("environment_saga", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ArchetypeVersion", b =>
                {
                    b.HasOne("Pdp.ControlPlane.Registry.Entities.Archetype", "Archetype")
                        .WithMany("Versions")
                        .HasForeignKey("ArchetypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archetype_versions_archetypes_archetype_name");

                    b.Navigation("Archetype");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ProvisioningRun", b =>
                {
                    b.HasOne("Pdp.ControlPlane.Registry.Entities.Environment", "Environment")
                        .WithMany("Runs")
                        .HasForeignKey("EnvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_runs_environments_env_id");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.WorkloadDetails", b =>
                {
                    b.HasOne("Pdp.ControlPlane.Registry.Entities.Environment", "Environment")
                        .WithOne()
                        .HasForeignKey("Pdp.ControlPlane.Registry.Entities.WorkloadDetails", "EnvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workloads_environments_env_id");

                    b.HasOne("Pdp.ControlPlane.Registry.Entities.ArchetypeVersion", null)
                        .WithMany()
                        .HasForeignKey("ArchetypeName", "ArchetypeVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workloads_archetype_versions_archetype_name_archetype_versi");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Archetype", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Environment", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
