// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pdp.ControlPlane.Registry;

#nullable disable

namespace Pdp.ControlPlane.Registry.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    [Migration("20260617204456_InitialRegistrySchema")]
    partial class InitialRegistrySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registry")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Environment", b =>
                {
                    b.Property<Guid>("EnvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("env_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<IPNetwork?>("SpokeCidr")
                        .HasColumnType("cidr")
                        .HasColumnName("spoke_cidr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EnvId")
                        .HasName("pk_environments");

                    b.HasIndex("Kind", "Subscription", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_environment_natural_key");

                    b.ToTable("environments", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ProvisioningRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DispatchInputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dispatch_inputs");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("EnvId")
                        .HasColumnType("uuid")
                        .HasColumnName("env_id");

                    b.Property<long?>("GitHubRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_run_id");

                    b.Property<string>("GitHubRunUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_run_url");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("PlanSummary")
                        .HasColumnType("text")
                        .HasColumnName("plan_summary");

                    b.Property<string>("TrackedBy")
                        .HasColumnType("text")
                        .HasColumnName("tracked_by");

                    b.Property<string>("WorkflowFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_file");

                    b.HasKey("RunId")
                        .HasName("pk_provisioning_runs");

                    b.HasIndex("EnvId")
                        .HasDatabaseName("ix_provisioning_runs_env_id");

                    b.HasIndex("EnvId", "GitHubRunId")
                        .IsUnique()
                        .HasDatabaseName("uq_provisioning_run_github_run")
                        .HasFilter("github_run_id IS NOT NULL");

                    b.ToTable("provisioning_runs", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.EnvironmentSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("text")
                        .HasColumnName("current_phase");

                    b.Property<Guid?>("CurrentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_run_id");

                    b.Property<bool>("PendingConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("pending_confirmation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_environment_saga");

                    b.ToTable("environment_saga", "registry");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.ProvisioningRun", b =>
                {
                    b.HasOne("Pdp.ControlPlane.Registry.Entities.Environment", "Environment")
                        .WithMany("Runs")
                        .HasForeignKey("EnvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_runs_environments_env_id");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Pdp.ControlPlane.Registry.Entities.Environment", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
